#!/bin/bash
# First time setup

source $ZSH_CUSTOM/scripts/script.sh

command -v stow
[[ $? -ne 0 ]] && install-pkg stow

tools=(
    # bash
    emacs
    git
    vim
    zsh
)

echo ${tools[@]} | xargs stow -Rv

cmds=(
    fdclone
    fzf
    ripgrep
    zsh-autosuggestions
)

echo ${cmds[@]} | xargs bash ./sync

exit
