#!/bin/bash
# First time setup

source $ZSH_CUSTOM/scripts/script.sh

command -v stow
[[ $? -ne 0 ]] && install-pkg stow

tools=(
    # bash
    emacs
    git
    vim
    zsh
)

echo ${tools[@]} | xargs stow -Rv

kutty_tools=(
    fdclone # fd
    fzf
    ripgrep
    zsh-autosuggestions
    zsh-syntax-highlighting
)

echo ${kutty_tools[@]} | xargs bash ./sync

exit
