#!/bin/bash
# Install small tools you use.

source $ZSH_CUSTOM/scripts/script.sh

for item in $@
do
    case "$item" in
        zsh-autosuggestions)
            clone_path=$ZSH_CUSTOM/plugins/zsh-autosuggestions
            mkdir -p $clone_path
            git clone https://github.com/zsh-users/zsh-autosuggestions "$clone_path"
            [[ $? -eq 0 ]] && printf "\nzsh-autosuggestions cloned to $clone_path."
            ;;
        fzf|ripgrep|fdclone)
            install-pkg $item
    esac
done
