#+TITLE: Emacs
This is my repository to keep track of my progress in Emacs!

*** Issues :/
It is still not plug and play. Following are some of the issues you may face.
***** gls not found
Comment out the below line if you're not in OSX.
#+begin_src emacs-lisp
(insert-directory-program "ls")   ; ls in OSX can't group contents by type. Use gls from coreutils
#+end_src

***** org-tempo not found
#+begin_example
M-x packages-list-packages    (for some reason, package-install doesn't list org)
search and install 'org'
#+end_example

***** fonts
****** Cantarell
1. Download the font from [[https://fonts.google.com/specimen/Cantarell][fonts.google.com]] and do the following
2. Follow this [[https://support.apple.com/en-us/HT201749][support page]]. The same can be done in Ubuntu as well.

****** Fira Code Retina
1. The [[https://github.com/tonsky/FiraCode][Fira Code]] repository has awesome installation instructions for all distributions.

*** Things you can expect sometime soon
  - Detailed description of Init.org along with their usage
  - Achieve plug and play (atleast except for fonts)

*** Thanks
I am fairly a beginner in Emacs, so if you think, there are better ways to achieve some functionalities, please do let me know.

I started with Emacs by following [[https://github.com/daviwil][David Wilson]].
A decent amount of my emacs configuration is taken from his [[https://github.com/daviwil/emacs-from-scratch][emacs-from-scratch]] repository.
And I would like to thank everyone who helped me get started with Emacs.

